apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-team-argocd-sync-fail-notification-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: team-notification
        image: curlimages/curl     
        command: 
        - 'curl'
        - '-XPOST'
        - '-H'
        - 'Content-type: application/json'
        - '-d'
        - '{"text": "ArgoCD sync for nginx deployment failed"}'
        - '<webhook url>'
      restartPolicy: Never
  backoffLimit: 2
