apiVersion: batch/v1
kind: Pod
metadata:
  name: app-team-argocd-sync-fail-notification
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: team-notification
        image: ubuntu    
        command: ["echo", "This is pre-sync"]
      restartPolicy: Never
 