apiVersion: batch/v1
kind: Job
metadata:
  name: app-team-argocd-sync-fail-notification
  annotations:
    #argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    #argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: team-notification
        image: curlimages/curl     
        command: 
        - 'curl'
        - '-H'
        - 'Content-type: application/json'
        - '-d'
        - '{"text": "ArgoCD sync for nginx demo app has failed!"}'
        - 'https://relhealth.webhook.office.com/webhookb2/a5e04e46-e370-482b-b122-b2ec90fa4bec@babd2876-4a15-44e3-98f0-f1126a52496a/IncomingWebhook/5324260c66644102bdc2d67be2b68ffe/ca5eb201-da10-42c7-b2d5-bae35e5c09d1'
      restartPolicy: Never
  backoffLimit: 2