apiVersion: batch/v1
kind: Job
metadata:
  name: app-team-argocd-sync-fail-notification
  annotations:
    argocd.argoproj.io/hook: SyncFail
    #argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: team-notification
        image: curlimages/curl     
        command: 
        - 'curl'
        - '-H'
        - 'Content-type: application/json'
        - '-d'
        - '{"text": "ArgoCD sync for nginx demo app has failed for syncfail hook!"}'
        - '<webhook url here>'
      restartPolicy: Never
  backoffLimit: 2