apiVersion: batch/v1
kind: Job
metadata:
  name: app-team-argocd-sync-fail-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    #argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    #argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: team-notification
        image: curlimages/curl     
        command: 
        - '/bin/sh'
        - '-c'
        - 'echo "Starting..." ; sleep 15s ; echo "Slept" ; curl -H "Content-type: application/json" -d "{\"text\": \"ArgoCD sync for nginx demo app failed\"}" <webhook url here> ; echo "Sent curl" ; echo $?'
      restartPolicy: Never
  backoffLimit: 2
  #ttlSecondsAfterFinished: 60
