apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-inline-example
resources:
  - argocd-monitoring.yaml
patches:
  - target:
      kind: Job
      name: app-team-argocd-sync-fail-notification
    patch: |-
      - op: remove
        path: /spec/ttlSecondsAfterFinished